python3 inverse_folding/inverse_folding/sample.py \
    --model=checkpoints/progen2-base \
    --rep_model=ckpt/coords_encoder  \
    --device=cuda \
    --batch_size=8 \
    --iters=1 \
    --max_length=512 \
    --t=0.1 \
    --k=10 \
    --prompt="1MEVVIVTGMSGAGK" \
    --coords='coords.pkl'